theme = "kyle"

[editor]
auto-format = false
auto-pairs = false
end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "hint"
jump-label-alphabet = "abcdefhiklmnorstuvwxz"
mouse = false
popup-border = "all"
smart-tab.enable = false

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
m = ":set end-of-line-diagnostics hint"
M = ":set end-of-line-diagnostics disable"
